# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c34b095cb2e904fea93130cf253e825695ba3d4f5e0b0f72b36898c77f4af9e3d2f1ab674f4771d4663e2613a88d76d19c24a4f4c34eca6e58d593dadd51268

test:
  secret_key_base: b215319a48f6e2305c190a12b91e709ca11b640ac9ee42848968cee1baf6c9ad6d38d2b7e45b3789b792f5f59ba71bd951f18e6d2af84eb0c491f150bf0c744e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
